services:
  tmkms:
    container_name: tmkms
    image: babylonlabs-io/tmkms:latest
    volumes:
      - ../.testnets/tmkms:/tmkms
    command: tmkms start -c /tmkms/config/tmkms.toml
    networks:
      localnet:
        ipv4_address: 192.168.10.18
    ports:
      - "26658:26658"

  babylondnode0:
    container_name: babylondnode0
    image: "babylonlabs-io/babylond"
    command: >
      babylond --home /babylondhome start --log_level trace --trace --log_format 'plain' 2>&1 | tee /babylondhome/babylond.log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - BABYLON_BLS_PASSWORD=password
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ../.testnets/node0/babylond:/babylondhome:Z
      - ../.testnets/node0/contracts:/contracts:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2
    depends_on:
      - tmkms

  babylondnode1:
    container_name: babylondnode1
    image: "babylonlabs-io/babylond"
    command: >
      babylond --home /babylondhome start --log_level trace --trace --log_format 'plain' 2>&1 | tee /babylondhome/babylond.log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - BABYLON_BLS_PASSWORD=password      
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - ../.testnets/node1/babylond:/babylondhome:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  bitcoindsim:
    build:
      context: contrib/images/bitcoindsim/
      dockerfile: ./Dockerfile
    image: babylonlabs-io/bitcoindsim:latest
    platform: linux/amd64
    container_name: bitcoindsim
    networks:
      localnet:
        ipv4_address: 192.168.10.30
    environment:
      - ZMQ_SEQUENCE_PORT=29000
      - ZMQ_RAWBLOCK_PORT=29001
      - ZMQ_RAWTR_PORT=29002
      - RPC_PORT=18443
      - RPC_USER=rpcuser
      - RPC_PASS=rpcpass
      - WALLET_PASS=walletpass
      - WALLET_NAME=default
      - BTCSTAKER_WALLET_NAME=btcstaker
      - BTCSTAKER_WALLET_ADDR_COUNT=3
      - GENERATE_INTERVAL_SECS=10
    ports:
      - "18443:18443"
      - "29000-29002:29000-29002"
    volumes:
      - ../.testnets/bitcoin:/bitcoindsim/.bitcoin:Z

  vigilante-reporter:
    container_name: vigilante-reporter
    image: babylonlabs-io/vigilante
    command: >
      vigilante reporter --config /home/vigilante/config/vigilante.yml 2>&1 | tee /home/vigilante/config/reporter.log
    networks:
      localnet:
        ipv4_address: 192.168.10.7
    volumes:
      - ../.testnets/vigilante:/home/vigilante/config
    depends_on:
      - bitcoindsim
      - babylondnode0
    restart: unless-stopped

  vigilante-submitter:
    container_name: vigilante-submitter
    image: babylonlabs-io/vigilante
    command: >
      vigilante submitter --config /home/vigilante/config/vigilante.yml 2>&1 | tee /home/vigilante/config/submitter.log
    networks:
      localnet:
        ipv4_address: 192.168.10.8
    volumes:
      - ../.testnets/vigilante:/home/vigilante/config
    depends_on:
      - bitcoindsim
      - babylondnode0
    restart: unless-stopped

  vigilante-monitor:
    container_name: vigilante-monitor
    image: babylonlabs-io/vigilante
    command: >
      vigilante monitor --config /home/vigilante/config/vigilante.yml --genesis /home/vigilante/config/bbnconfig/genesis.json 2>&1 | tee /home/vigilante/config/monitor.log
    networks:
      localnet:
        ipv4_address: 192.168.10.9
    volumes:
      - ../.testnets/vigilante:/home/vigilante/config
    depends_on:
      - bitcoindsim
      - babylondnode0
    restart: unless-stopped

  vigilante-bstracker:
    container_name: vigilante-bstracker
    image: babylonlabs-io/vigilante
    command: >
      vigilante bstracker --config /home/vigilante/config/vigilante.yml 2>&1 | tee /home/vigilante/config/unbonding-watcher.log
    networks:
      localnet:
        ipv4_address: 192.168.10.10
    volumes:
      - ../.testnets/vigilante:/home/vigilante/config
    depends_on:
      - bitcoindsim
      - babylondnode0
    restart: unless-stopped

  btc-staker:
    container_name: btc-staker
    image: babylonlabs-io/btc-staker
    networks:
      localnet:
        ipv4_address: 192.168.10.11
    environment:
      - BTCSTAKER_USERNAME=rpcuser
      - BTCSTAKER_PASSWORD=rpcpass        
    volumes:
      - ../.testnets/btc-staker:/home/btcstaker/.stakerd
    ports:
      - "15912:15812"
    depends_on:
      - bitcoindsim
      - babylondnode0
    restart: unless-stopped

  finality-provider:
    container_name: finality-provider
    image: babylonlabs-io/finality-provider
    command: fpd start
    networks:
      localnet:
        ipv4_address: 192.168.10.12
    ports:
      - "15822:15812"
    volumes:
      - ../.testnets/finality-provider:/home/finality-provider/.fpd
    depends_on:
      - babylondnode0
    restart: unless-stopped

  eotsmanager:
    container_name: eotsmanager
    image: babylonlabs-io/finality-provider
    command: eotsd start
    networks:
      localnet:
        ipv4_address: 192.168.10.14
    ports:
      - "15825:15813"
    volumes:
      - ../.testnets/eotsmanager:/home/finality-provider/.eotsd
    depends_on:
      - babylondnode0
    restart: unless-stopped

  covenant-signer:
    container_name: covenant-signer
    image: babylonlabs-io/covenant-signer
    command: covenant-signer start
    networks:
      localnet:
        ipv4_address: 192.168.10.16
    volumes:
      - ../.testnets/covenant-signer:/home/covenant-signer/.signer
    depends_on:
      - babylondnode0
    restart: unless-stopped

  covenant-emulator:
    container_name: covenant-emulator
    image: babylonlabs-io/covenant-emulator
    command: covd start
    networks:
      localnet:
        ipv4_address: 192.168.10.17
    volumes:
      - ../.testnets/covenant-emulator:/home/covenant-emulator/.covd
    depends_on:
      - babylondnode0
      - covenant-signer
    restart: unless-stopped

  electrs:
    image: mempool/electrs:v3.1.0
    container_name: electrs
    platform: linux/amd64
    networks:
      localnet:
        ipv4_address: 192.168.10.31
    depends_on:
      - bitcoindsim
    environment:
      - ELECTRS_NETWORK=regtest
      - ELECTRS_COOKIE=rpcuser:rpcpass
      - ELECTRS_DAEMON_RPC_ADDR=bitcoindsim:18443
      - ELECTRS_DB_DIR=/electrs/.electrs/db
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ../.testnets/electrs:/data:Z
      - ../.testnets/bitcoin:/bitcoin/.bitcoin:Z
    command:
      [ "--cookie", "rpcuser:rpcpass",
        "--network", "regtest",
        "--electrum-rpc-addr", "0.0.0.0:8080",
        "--http-addr", "0.0.0.0:3000",
        "--db-dir", "/electrs/.electrs/db/",
        "--daemon-rpc-addr", "bitcoindsim:18443",
        "--daemon-dir", "/bitcoin/.bitcoin",
        "-v",
        "--address-search",
        "--cors", "*",
        "--timestamp"
      ]


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25
